//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Lkb
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonServiceImplServiceSoapBinding", Namespace="http://service.person.service.eastcompeace.com/")]
    public partial class PersonServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertPersonFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertPersonOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertPersonCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertUserhouseOperationCompleted;
        
        /// <remarks/>
        public PersonServiceImplService() {
            this.Url = "http://220.191.208.83:9603/fpps/personService";
        }
        
        /// <remarks/>
        public event insertPersonFlowCompletedEventHandler insertPersonFlowCompleted;
        
        /// <remarks/>
        public event insertPersonCompletedEventHandler insertPersonCompleted;
        
        /// <remarks/>
        public event insertPersonCardCompletedEventHandler insertPersonCardCompleted;
        
        /// <remarks/>
        public event insertUserhouseCompletedEventHandler insertUserhouseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.person.service.eastcompeace.com/", ResponseNamespace="http://service.person.service.eastcompeace.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string insertPersonFlow([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("insertPersonFlow", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininsertPersonFlow(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insertPersonFlow", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinsertPersonFlow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertPersonFlowAsync(string arg0) {
            this.insertPersonFlowAsync(arg0, null);
        }
        
        /// <remarks/>
        public void insertPersonFlowAsync(string arg0, object userState) {
            if ((this.insertPersonFlowOperationCompleted == null)) {
                this.insertPersonFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertPersonFlowOperationCompleted);
            }
            this.InvokeAsync("insertPersonFlow", new object[] {
                        arg0}, this.insertPersonFlowOperationCompleted, userState);
        }
        
        private void OninsertPersonFlowOperationCompleted(object arg) {
            if ((this.insertPersonFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertPersonFlowCompleted(this, new insertPersonFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.person.service.eastcompeace.com/", ResponseNamespace="http://service.person.service.eastcompeace.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string insertPerson([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("insertPerson", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininsertPerson(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insertPerson", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinsertPerson(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertPersonAsync(string arg0) {
            this.insertPersonAsync(arg0, null);
        }
        
        /// <remarks/>
        public void insertPersonAsync(string arg0, object userState) {
            if ((this.insertPersonOperationCompleted == null)) {
                this.insertPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertPersonOperationCompleted);
            }
            this.InvokeAsync("insertPerson", new object[] {
                        arg0}, this.insertPersonOperationCompleted, userState);
        }
        
        private void OninsertPersonOperationCompleted(object arg) {
            if ((this.insertPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertPersonCompleted(this, new insertPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.person.service.eastcompeace.com/", ResponseNamespace="http://service.person.service.eastcompeace.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string insertPersonCard([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("insertPersonCard", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininsertPersonCard(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insertPersonCard", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinsertPersonCard(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertPersonCardAsync(string arg0) {
            this.insertPersonCardAsync(arg0, null);
        }
        
        /// <remarks/>
        public void insertPersonCardAsync(string arg0, object userState) {
            if ((this.insertPersonCardOperationCompleted == null)) {
                this.insertPersonCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertPersonCardOperationCompleted);
            }
            this.InvokeAsync("insertPersonCard", new object[] {
                        arg0}, this.insertPersonCardOperationCompleted, userState);
        }
        
        private void OninsertPersonCardOperationCompleted(object arg) {
            if ((this.insertPersonCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertPersonCardCompleted(this, new insertPersonCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.person.service.eastcompeace.com/", ResponseNamespace="http://service.person.service.eastcompeace.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string insertUserhouse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("insertUserhouse", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininsertUserhouse(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insertUserhouse", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinsertUserhouse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertUserhouseAsync(string arg0) {
            this.insertUserhouseAsync(arg0, null);
        }
        
        /// <remarks/>
        public void insertUserhouseAsync(string arg0, object userState) {
            if ((this.insertUserhouseOperationCompleted == null)) {
                this.insertUserhouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertUserhouseOperationCompleted);
            }
            this.InvokeAsync("insertUserhouse", new object[] {
                        arg0}, this.insertUserhouseOperationCompleted, userState);
        }
        
        private void OninsertUserhouseOperationCompleted(object arg) {
            if ((this.insertUserhouseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertUserhouseCompleted(this, new insertUserhouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void insertPersonFlowCompletedEventHandler(object sender, insertPersonFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertPersonFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertPersonFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void insertPersonCompletedEventHandler(object sender, insertPersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void insertPersonCardCompletedEventHandler(object sender, insertPersonCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertPersonCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertPersonCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void insertUserhouseCompletedEventHandler(object sender, insertUserhouseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertUserhouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertUserhouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
